### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe4 in position 2050: illegal multibyte sequence

### ISSUE THREAD

**Issue by 647LiuSQ** [SajadMo/SleepEEGNet#4]
I get the following when I run the code:

Traceback (most recent call last):
  File "D:/report/SleepEEGNet-master/prepare_physionet.py", line 226, in <module>
    main()
  File "D:/report/SleepEEGNet-master/prepare_physionet.py", line 110, in main
    reader_raw.read_header()
  File "D:\report\SleepEEGNet-master\dhedfreader.py", line 90, in read_header
    self.header = h = edf_header(self.file)
  File "D:\report\SleepEEGNet-master\dhedfreader.py", line 49, in edf_header
    h['local_subject_id'] = f.read(80).strip()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe4 in position 2050: illegal multibyte sequence

**Comment by MousaviSajad** [comment]
Hello,
The below link may help you resolve the issue:
https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

Regards,
Sajad
