### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 2050: invalid continuation byte

### ISSUE THREAD

**Issue by Wensi-Tang** [SajadMo/SleepEEGNet#5]
Traceback (most recent call last):
  File "prepare_physionet.py", line 226, in <module>
    main()
  File "prepare_physionet.py", line 110, in main
    reader_raw.read_header()
  File "/home/tangw/Desktop/SleepEEGNet/SleepEEGNet_tensorflow/dhedfreader.py", line 90, in read_header
    self.header = h = edf_header(self.file)
  File "/home/tangw/Desktop/SleepEEGNet/SleepEEGNet_tensorflow/dhedfreader.py", line 46, in edf_header
    assert f.read(8) == '0       '
  File "/home/tangw/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 2050: invalid continuation byte

**Comment by Wensi-Tang** [comment]
I run it will python2.7 and the problem solved
